### ISSUE TITLE
Decode As...?

### ISSUE THREAD

**Issue by zoulja** [gcla/termshark#104]
Hi
I have many scenarios where service is running on non-standard port, so very often I have to use 'Decode As...' option to let Wireshark know what this protocol really is.
As I understand there is no direct option in Termshark right now, but maybe you can suggest some workaround?

**Comment by gcla** [comment]
Hi @zoulja - I have the following in `~/.config/termshark/termshark.toml`:

```toml
[main]
  tshark-args = ["-d","udp.port==2075,cflow","-d","udp.port==9191,cflow","-d","udp.port==2055,cflow","-d","udp.port==2095,cflow"]
```

The arguments will be added to each invocation of tshark. Will something like that work for your scenario?
