### ISSUE TITLE
make termshark packet columns configurable

### ISSUE THREAD

**Issue by gcla** [gcla/termshark#45]
A feature request stemming from a bug reported by @jJit0

When I look into this, take a look at `~/.wireshark/preferences`, `gui.column.format`

**Comment by gcla** [comment]
It's been a long while @jJit0 but I am finally working on this now...

**Comment by zoulja** [comment]
Hi. Any plans on this? Actually I'm interested in columns+profiles setting
For example for HTTP we need one set of columns(profile) and for SNMP - another set(profile)
Possibility to switch profiles in 2 clicks would be nice

**Comment by gcla** [comment]
Hi @zoulja - yes, though I didn't complete it for v2.2 unfortunately. I think I need to do some work on the underlying table widget to make its layout more flexible.

**Comment by gcla** [comment]
Hi @jJit0 and @zoulja ,

I've pushed a branch called configcolumns with a first stab at implementing configurable columns for termshark's packet list view. If you have time, would you mind giving it a try and letting me know what you think? Any feedback at all would be great. There's a new field that you can set in `termshark.toml` to configure the columns. Here's my config:

```toml
[main]
  column-format = ["%m", "%Yut", "%s", "%d", "%p", "%L", "%i", "%B"]
```

You can see these tokens if you run:

```
tshark -G column-formats
```

Termshark will run that behind the scenes to generate the list of all valid token names for columns. At startup, termshark will check your columns against this master list and discard any that are invalid, with a warning in the logs. If all are invalid, it will fall back to a safe set of columns (those that termshark uses now).

You can give the columns your own short names like this:

```toml
[main]
  column-format = ["%m No.", "%Yut Time", "%s Src", "%d Dst", "%p Proto", "%L Len", "%i Info", "%V vsan", "%B cumb"]
```

Here's how to build:

```
git clone https://github.com/gcla/termshark
cd termshark
git checkout configcolumns
export GO111MODULE=on
go install ./...
```

Then the binary will be `~/go/bin/termshark`. Or you can get prebuilt binaries from these links:

Linux: https://storage.googleapis.com/termshark/d35d83322b03f93ee4898a0bd8103761d40fd2cc/termshark_linux_amd64/termshark

macOS: https://storage.googleapis.com/termshark/d35d83322b03f93ee4898a0bd8103761d40fd2cc/termshark_darwin_amd64/termshark

Windows: https://storage.googleapis.com/termshark/d35d83322b03f93ee4898a0bd8103761d40fd2cc/termshark_windows_amd64/termshark.exe

There's no GUI support yet for configuring these columns. I'm not sure if it's needed. What do you think?

**Comment by zoulja** [comment]
Hi. By some reason it doesn't work for me, I don't see any difference when I change columns
```
% ./termshark -v                                                                                                                                                                                         
termshark v2.2.0+
```

I tried to modify this configuration file ~/.config/termshark/termshark.toml

**Comment by gcla** [comment]
Sorry @zoulja , I'm not sure what went wrong. I just tried with a freshly created Linux user and the Linux binary above. Here's the config termshark wrote out with my extra field added. I added two '%Yut' fields so I could see the difference quickly:
```toml
[main]
  color-tsharks = ["/usr/bin/tshark"]
  column-format = ["%m", "%Yut", "%Yut", "%s", "%d", "%p", "%L", "%i", "%B"]
  last-used-tshark = "/usr/bin/tshark"
  recent-files = ["/tmp/mix2.pcap"]
  validated-tsharks = ["/usr/bin/tshark"]
```
![image](https://user-images.githubusercontent.com/45680/105530437-c93d3600-5cb5-11eb-9744-b9236774b54c.png)

Would you mind pasting the relevant part of your toml config file?
