### ISSUE TITLE
Add custom theme or base16 theme

### ISSUE THREAD

**Issue by kevinhwang91** [gcla/termshark#95]
### Is your feature request related to a problem? Please describe.
The dark mode's background is pure dark, my all TUI Apps and terminal background is `#202326`.
Maybe this feature is a personal aesthetic issue, but the most TUI Apps can customize the theme or obey base16 that make the theme of App and terminal look more matching.

### Describe the solution you'd like
If the workload of the custom theme is heavy, base16 is a better choice.

**Comment by gcla** [comment]
Thanks @kevinhwang91 , I confess I'd never heard of base16 themes... I'll read up on them tonight.

**Comment by gcla** [comment]
You think you know something, then one google and a whole new world opens up... I think I can do something to make these customizable.

**Comment by gcla** [comment]
Hi @kevinhwang91 - I've pushed a branch called themes with my first attempt at your request. Here are links to binaries - please do try it out if you have time and let me know. I didn't merge this to master yet because maybe some changes will be needed yet. I've exposed all termshark's palette keys as theme settings and these can be configured via the toml config file - `~/.config/termshark/termshark.toml` on Linux. I'll paste an example below, my attempt to use the dracula theme's colors (https://draculatheme.com/). You can't set these in the UI yet, so you'll need to edit the toml file somewhere. Here are the rules:

- add dark-mode rules under `[themes.rules.dark]`
- add light mode rules under `[themes.rules.light]`
- define colors as `<name> = <value>`. The value can refer to another key, or use a syntax like #rrggbb (you can use other gowid color names too).
- define theme rules as `<name> = [fgcolor, bgcolor]`

This could be made base16-compatible by having a standard set of color key names e.g. `base16-{0..f}` and then referring to those only in the theme keys (like `button-focus`). I haven't done that yet - instead I just copied dracula key names and colors from emacs and then used those in the theme rules.

These work best if your terminal supports truecolor - I used terminator on Linux, and I have `COLORTERM=truecolor` and `TERM=xterm-256color` in my environment. Here are the binaries:

Linux: https://storage.googleapis.com/termshark/e0737277d0ff77612f19d3cb5d13ada01a4d1212/termshark_linux_amd64/termshark

macOS: https://storage.googleapis.com/termshark/e0737277d0ff77612f19d3cb5d13ada01a4d1212/termshark_darwin_amd64/termshark

Windows: https://storage.googleapis.com/termshark/e0737277d0ff77612f19d3cb5d13ada01a4d1212/termshark_windows_amd64/termshark.exe

**Comment by gcla** [comment]
Here are the additions I made to `~/.config/termshark/termshark.toml`:

```toml
[themes]
  unused = "#79e11a"

  [themes.dracula]
    bg = "#282a36"
    bg2 = "#373844"
    bg3 = "#464752"
    bg4 = "#565761"
    black = "themes.dracula.bg"
    comment = "#6272a4"
    current = "#44475a"
    cyan = "#8be9fd"
    fg = "#f8f8f2"
    fg2 = "#e2e2dc"
    fg3 = "#ccccc7"
    fg4 = "#b6b6b2"
    green = "#50fa7b"
    orange = "#ffb86c"
    other-blue = "#0189cc"
    pink = "#ff79c6"
    purple = "#bd93f9"
    red = "#ff5555"
    white = "themes.dracula.fg"
    yellow = "#f1fa8c"

  [themes.rules]

    [themes.rules.dark]
      button = ["themes.dracula.white","themes.dracula.black"]
      button-focus = ["themes.dracula.black","themes.dracula.purple"]
      button-selected = ["themes.dracula.white","themes.dracula.black"]
      cmdline = ["themes.dracula.black","themes.dracula.yellow"]
      cmdline-button = ["themes.dracula.yellow","themes.dracula.black"]
      copy-mode = ["themes.dracula.black","themes.dracula.yellow"]
      copy-mode-alt = ["themes.dracula.yellow","themes.dracula.black"]
      copy-mode-label = ["themes.dracula.white","themes.dracula.red"]
      current-capture = ["themes.dracula.white","themes.unused"]
      default = ["themes.dracula.white","themes.dracula.black"]
      dialog = ["themes.dracula.black","themes.dracula.yellow"]
      dialog-button = ["themes.dracula.yellow","themes.dracula.black"]
      filter-intermediate = ["themes.dracula.black","themes.dracula.orange"]
      filter-invalid = ["themes.dracula.black","themes.dracula.red"]
      filter-menu = ["themes.dracula.white","themes.dracula.black"]
      filter-valid = ["themes.dracula.black","themes.dracula.green"]
      hex-byte-selected = ["themes.dracula.black","themes.dracula.purple"]
      hex-byte-unselected = ["themes.dracula.white","themes.dracula.black"]
      hex-field-selected = ["themes.dracula.black","themes.dracula.cyan"]
      hex-field-unselected = ["themes.dracula.black","themes.dracula.white"]
      hex-interval-selected = ["themes.dracula.white","themes.dracula.bg4"]
      hex-interval-unselected = ["themes.dracula.white","themes.dracula.bg3"]
      hex-layer-selected = ["themes.dracula.white","themes.dracula.bg4"]
      hex-layer-unselected = ["themes.dracula.white","themes.dracula.bg3"]
      packet-list-cell-focus = ["themes.dracula.black","themes.dracula.purple"]
      packet-list-cell-selected = ["themes.dracula.white","themes.dracula.bg4"]
      packet-list-row-focus = ["themes.dracula.bg4","themes.dracula.cyan"]
      packet-list-row-selected = ["themes.dracula.white","themes.dracula.bg3"]
      packet-struct-focus = ["themes.dracula.bg4","themes.dracula.cyan"]
      packet-struct-selected = ["themes.dracula.black","themes.dracula.bg4"]
      progress-complete = ["themes.dracula.white","themes.dracula.purple"]
      progress-default = ["themes.dracula.white","themes.dracula.black"]
      progress-spinner = ["themes.dracula.yellow","themes.dracula.purple"]
      spinner = ["themes.dracula.yellow","themes.dracula.black"]
      stream-client = ["themes.dracula.black","themes.dracula.red"]
      stream-match = ["themes.dracula.black","themes.dracula.yellow"]
      stream-search = ["themes.dracula.black","themes.dracula.white"]
      stream-server = ["themes.dracula.cyan","themes.dracula.comment"]
      title = ["themes.dracula.red","themes.unused"]

    [themes.rules.light]
      button = ["themes.dracula.black","themes.dracula.white"]
      button-focus = ["themes.dracula.black","themes.dracula.purple"]
      button-selected = ["themes.dracula.black","themes.dracula.fg4"]
      cmdline = ["themes.dracula.black","themes.dracula.yellow"]
      cmdline-button = ["themes.dracula.yellow","themes.dracula.black"]
      copy-mode = ["themes.dracula.white","themes.dracula.yellow"]
      copy-mode-alt = ["themes.dracula.yellow","themes.dracula.white"]
      copy-mode-label = ["themes.dracula.black","themes.dracula.red"]
      current-capture = ["themes.dracula.black","themes.unused"]
      default = ["themes.dracula.black","themes.dracula.white"]
      dialog = ["themes.dracula.black","themes.dracula.yellow"]
      dialog-button = ["themes.dracula.yellow","themes.dracula.black"]
      filter-intermediate = ["themes.dracula.black","themes.dracula.orange"]
      filter-invalid = ["themes.dracula.black","themes.dracula.red"]
      filter-menu = ["themes.dracula.black","themes.dracula.white"]
      filter-valid = ["themes.dracula.black","themes.dracula.green"]
      hex-byte-selected = ["themes.dracula.black","themes.dracula.purple"]
      hex-byte-unselected = ["themes.dracula.black","themes.dracula.white"]
      hex-field-selected = ["themes.dracula.black","themes.dracula.cyan"]
      hex-field-unselected = ["themes.dracula.black","themes.dracula.bg4"]
      hex-interval-selected = ["themes.dracula.white","themes.dracula.bg4"]
      hex-interval-unselected = ["themes.dracula.black","themes.dracula.fg3"]
      hex-layer-selected = ["themes.dracula.white","themes.dracula.bg4"]
      hex-layer-unselected = ["themes.dracula.black","themes.dracula.fg3"]
      packet-list-cell-focus = ["themes.dracula.black","themes.dracula.purple"]
      packet-list-cell-selected = ["themes.dracula.black","themes.dracula.fg4"]
      packet-list-row-focus = ["themes.dracula.black","themes.dracula.cyan"]
      packet-list-row-selected = ["themes.dracula.black","themes.dracula.fg3"]
      packet-struct-focus = ["themes.dracula.black","themes.dracula.cyan"]
      packet-struct-selected = ["themes.dracula.black","themes.dracula.fg3"]
      progress-complete = ["themes.dracula.white","themes.dracula.purple"]
      progress-default = ["themes.dracula.white","themes.dracula.black"]
      progress-spinner = ["themes.dracula.yellow","themes.dracula.black"]
      spinner = ["themes.dracula.yellow","themes.dracula.white"]
      stream-client = ["themes.dracula.white","themes.dracula.red"]
      stream-match = ["themes.dracula.white","themes.dracula.yellow"]
      stream-search = ["themes.dracula.white","themes.dracula.black"]
      stream-server = ["themes.dracula.cyan","themes.dracula.comment"]
      title = ["themes.dracula.red","themes.unused"]
```

**Comment by gcla** [comment]
Here's what it looks like in terminator on Ubuntu:

![image](https://user-images.githubusercontent.com/45680/92351448-c1d01400-f0a9-11ea-9926-412d5250f11a.png)

**Comment by kevinhwang91** [comment]
LGTM after change a few color style!!
![image](https://user-images.githubusercontent.com/17562139/92362265-51b1a480-f122-11ea-8443-ebc4a70d4e14.png)

Btw, I suggest that separating the `data` and `configuration` into different files, so I can push termshark's config to my dotfiles.

**Comment by gcla** [comment]
Hi @kevinhwang91 - I've pushed a few more changes this evening that separate the themes out from the main `termshark.toml`, as you suggested. Now `termshark.toml` contains one new key e.g.

```toml
[main]
  theme = "dracula"
```

If you set this, then termshark will look for a theme called `dracula` as follows:

- as a file called `~/.config/termshark/themes/dracula.toml` (on Linux)
- in its mini built-in database of themes (compressed and compiled in to the binary)

I'll paste the example `dracula.toml` below. I've tried to make it base16-compatible.

There are also a couple of new minibuffer commands:

![image](https://user-images.githubusercontent.com/45680/92858538-2f3eb600-f3c4-11ea-9f91-497bfbacda25.png)

and to go back to default colors:

![image](https://user-images.githubusercontent.com/45680/92858596-41205900-f3c4-11ea-9a9e-38659b00d307.png)

Of course, feedback most welcome!

**Comment by gcla** [comment]
`dracula.toml`:

https://github.com/gcla/termshark/blob/master/assets/themes/dracula.toml

```toml
unused = "#79e11a"

[dracula]
  base00 = "#282a36"
  base01 = "#373844"
  base02 = "#464752"
  base03 = "#565761"
  base04 = "#b6b6b2"
  base05 = "#ccccc7"
  base06 = "#e2e2dc"
  base07 = "#f8f8f2"
  base08 = "#ff5555"
  base09 = "#ffb86c"
  base0a = "#f1fa8c"
  base0b = "#50fa7b"
  base0c = "#8be9fd"
  base0d = "#6272a4"
  base0e = "#bd93f9"
  base0f = "#ff79c6"
  black = "dracula.base00"
  blue = "dracula.base0d"
  cyan = "dracula.base0c"
  green = "dracula.base0b"
  magenta = "dracula.base0f"
  orange = "dracula.base09"
  purple = "dracula.base0e"
  red = "dracula.base08"
  white = "dracula.base07"
  yellow = "dracula.base0a"

[dark]
  button = ["dracula.white","dracula.black"]
  button-focus = ["dracula.black","dracula.purple"]
  button-selected = ["dracula.white","dracula.black"]
  cmdline = ["dracula.black","dracula.yellow"]
  cmdline-button = ["dracula.yellow","dracula.black"]
  copy-mode = ["dracula.black","dracula.yellow"]
  copy-mode-alt = ["dracula.yellow","dracula.black"]
  copy-mode-label = ["dracula.white","dracula.red"]
  current-capture = ["dracula.white","unused"]
  dialog = ["dracula.black","dracula.yellow"]
  dialog-button = ["dracula.yellow","dracula.black"]
  default = ["dracula.white","dracula.black"]
  filter-intermediate = ["dracula.black","dracula.orange"]
  filter-invalid = ["dracula.black","dracula.red"]
  filter-menu = ["dracula.white","dracula.black"]
  filter-valid = ["dracula.black","dracula.green"]
  hex-byte-selected = ["dracula.black","dracula.purple"]
  hex-byte-unselected = ["dracula.white","dracula.black"]
  hex-field-selected = ["dracula.black","dracula.cyan"]
  hex-field-unselected = ["dracula.black","dracula.white"]
  hex-interval-selected = ["dracula.white","dracula.base03"]
  hex-interval-unselected = ["dracula.white","dracula.base02"]
  hex-layer-selected = ["dracula.white","dracula.base03"]
  hex-layer-unselected = ["dracula.white","dracula.base02"]
  packet-list-cell-focus = ["dracula.black","dracula.purple"]
  packet-list-cell-selected = ["dracula.white","dracula.base03"]
  packet-list-row-focus = ["dracula.base03","dracula.cyan"]
  packet-list-row-selected = ["dracula.white","dracula.base02"]
  packet-struct-focus = ["dracula.black","dracula.cyan"]
  packet-struct-selected = ["dracula.black","dracula.base03"]
  progress-complete = ["dracula.white","dracula.purple"]
  progress-default = ["dracula.white","dracula.black"]
  progress-spinner = ["dracula.yellow","dracula.purple"]
  spinner = ["dracula.yellow","dracula.black"]
  stream-client = ["dracula.black","dracula.red"]
  stream-match = ["dracula.black","dracula.yellow"]
  stream-search = ["dracula.black","dracula.white"]
  stream-server = ["dracula.cyan","dracula.blue"]
  title = ["dracula.red","unused"]

[light]
  button = ["dracula.black","dracula.white"]
  button-focus = ["dracula.black","dracula.purple"]
  button-selected = ["dracula.black","dracula.base04"]
  cmdline = ["dracula.black","dracula.yellow"]
  cmdline-button = ["dracula.yellow","dracula.black"]
  copy-mode = ["dracula.white","dracula.yellow"]
  copy-mode-alt = ["dracula.yellow","dracula.white"]
  copy-mode-label = ["dracula.black","dracula.red"]
  current-capture = ["dracula.black","unused"]
  dialog = ["dracula.black","dracula.yellow"]
  dialog-button = ["dracula.yellow","dracula.black"]
  default = ["dracula.black","dracula.white"]
  filter-intermediate = ["dracula.black","dracula.orange"]
  filter-invalid = ["dracula.black","dracula.red"]
  filter-menu = ["dracula.black","dracula.white"]
  filter-valid = ["dracula.black","dracula.green"]
  hex-byte-selected = ["dracula.black","dracula.purple"]
  hex-byte-unselected = ["dracula.black","dracula.white"]
  hex-field-selected = ["dracula.black","dracula.cyan"]
  hex-field-unselected = ["dracula.black","dracula.base03"]
  hex-interval-selected = ["dracula.white","dracula.base03"]
  hex-interval-unselected = ["dracula.black","dracula.base05"]
  hex-layer-selected = ["dracula.white","dracula.base03"]
  hex-layer-unselected = ["dracula.black","dracula.base05"]
  packet-list-cell-focus = ["dracula.black","dracula.purple"]
  packet-list-cell-selected = ["dracula.black","dracula.base04"]
  packet-list-row-focus = ["dracula.black","dracula.cyan"]
  packet-list-row-selected = ["dracula.black","dracula.base05"]
  packet-struct-focus = ["dracula.black","dracula.cyan"]
  packet-struct-selected = ["dracula.black","dracula.base05"]
  progress-complete = ["dracula.white","dracula.purple"]
  progress-default = ["dracula.white","dracula.black"]
  progress-spinner = ["dracula.yellow","dracula.black"]
  spinner = ["dracula.yellow","dracula.white"]
  stream-client = ["dracula.white","dracula.red"]
  stream-match = ["dracula.white","dracula.yellow"]
  stream-search = ["dracula.white","dracula.black"]
  stream-server = ["dracula.cyan","dracula.blue"]
  title = ["dracula.red","unused"]
```

**Comment by kevinhwang91** [comment]
It seems that I can't pass my terminal base16 color into termshark, 

```sh
for ((x=0; x<=15; x++));do
    echo -e "${x}:\033[48;5;${x}mcolor\033[0m"
done
```
It doesn't support base16 for now?

**Comment by gcla** [comment]
Hi @kevinhwang91 - I rearranged your colors a little and put them in the new theme format. I followed the order laid out here: http://chriskempson.com/projects/base16/ - dark to light, then the colors of the rainbow. I'll paste the theme below. Drop it in `~/.config/termshark/themes/kevin.toml`. To load it, you'll need a recent binary - try one of:

Linux: https://storage.googleapis.com/termshark/54075aa9e189888f4ee72e4f47ba67b10f81d526/termshark_linux_amd64/termshark

macOS: https://storage.googleapis.com/termshark/54075aa9e189888f4ee72e4f47ba67b10f81d526/termshark_darwin_amd64/termshark

Windows: https://storage.googleapis.com/termshark/54075aa9e189888f4ee72e4f47ba67b10f81d526/termshark_windows_amd64/termshark.exe

Then use the `theme` command at the cmdline:

![image](https://user-images.githubusercontent.com/45680/93000411-54cbdc80-f4f6-11ea-9b40-7df92970be69.png)

**Comment by gcla** [comment]
```toml

unused = "#79e11a"

[kevin]
  base00 = "#1D1F21"
  base01 = "#282A2E"
  base02 = "#373B41"
  base03 = "#969896"
  base04 = "#B4B7B4"
  base05 = "#C5C8C6"
  base06 = "#E0E0E0"
  base07 = "#FFFFFF"
  base08 = "#CC342B"
  base09 = "#F96A38"
  base0a = "#FBA922"
  base0b = "#198844"
  base0c = "#3971ED"
  base0d = "#3971ED"
  base0e = "#A36AC7"
  base0f = "#A36AC7"
  black = "kevin.base00"
  blue = "kevin.base0d"
  cyan = "kevin.base0c"
  green = "kevin.base0b"
  magenta = "kevin.base0f"
  orange = "kevin.base09"
  purple = "kevin.base0e"
  red = "kevin.base08"
  white = "kevin.base07"
  yellow = "kevin.base0a"

[dark]
  button = ["kevin.white","kevin.black"]
  button-focus = ["kevin.black","kevin.purple"]
  button-selected = ["kevin.white","kevin.black"]
  cmdline = ["kevin.black","kevin.yellow"]
  cmdline-button = ["kevin.yellow","kevin.black"]
  copy-mode = ["kevin.black","kevin.yellow"]
  copy-mode-alt = ["kevin.yellow","kevin.black"]
  copy-mode-label = ["kevin.white","kevin.red"]
  current-capture = ["kevin.white","themes.unused"]
  dialog = ["kevin.black","kevin.yellow"]
  dialog-button = ["kevin.yellow","kevin.black"]
  default = ["kevin.white","kevin.black"]
  filter-intermediate = ["kevin.black","kevin.orange"]
  filter-invalid = ["kevin.black","kevin.red"]
  filter-menu = ["kevin.white","kevin.black"]
  filter-valid = ["kevin.black","kevin.green"]
  hex-byte-selected = ["kevin.black","kevin.purple"]
  hex-byte-unselected = ["kevin.white","kevin.black"]
  hex-field-selected = ["kevin.black","kevin.cyan"]
  hex-field-unselected = ["kevin.black","kevin.white"]
  hex-interval-selected = ["kevin.white","kevin.base03"]
  hex-interval-unselected = ["kevin.white","kevin.base02"]
  hex-layer-selected = ["kevin.white","kevin.base03"]
  hex-layer-unselected = ["kevin.white","kevin.base02"]
  packet-list-cell-focus = ["kevin.black","kevin.purple"]
  packet-list-cell-selected = ["kevin.white","kevin.base03"]
  packet-list-row-focus = ["kevin.base03","kevin.cyan"]
  packet-list-row-selected = ["kevin.white","kevin.base02"]
  packet-struct-focus = ["kevin.black","kevin.cyan"]
  packet-struct-selected = ["kevin.black","kevin.base03"]
  progress-complete = ["kevin.white","kevin.purple"]
  progress-default = ["kevin.white","kevin.black"]
  progress-spinner = ["kevin.yellow","kevin.purple"]
  spinner = ["kevin.yellow","kevin.black"]
  stream-client = ["kevin.black","kevin.red"]
  stream-match = ["kevin.black","kevin.yellow"]
  stream-search = ["kevin.black","kevin.white"]
  stream-server = ["kevin.cyan","kevin.blue"]
  title = ["kevin.red","unused"]

[light]
  button = ["kevin.black","kevin.white"]
  button-focus = ["kevin.black","kevin.purple"]
  button-selected = ["kevin.black","kevin.base04"]
  cmdline = ["kevin.black","kevin.yellow"]
  cmdline-button = ["kevin.yellow","kevin.black"]
  copy-mode = ["kevin.white","kevin.yellow"]
  copy-mode-alt = ["kevin.yellow","kevin.white"]
  copy-mode-label = ["kevin.black","kevin.red"]
  current-capture = ["kevin.black","unused"]
  dialog = ["kevin.black","kevin.yellow"]
  dialog-button = ["kevin.yellow","kevin.black"]
  default = ["kevin.black","kevin.white"]
  filter-intermediate = ["kevin.black","kevin.orange"]
  filter-invalid = ["kevin.black","kevin.red"]
  filter-menu = ["kevin.black","kevin.white"]
  filter-valid = ["kevin.black","kevin.green"]
  hex-byte-selected = ["kevin.black","kevin.purple"]
  hex-byte-unselected = ["kevin.black","kevin.white"]
  hex-field-selected = ["kevin.black","kevin.cyan"]
  hex-field-unselected = ["kevin.black","kevin.base03"]
  hex-interval-selected = ["kevin.white","kevin.base03"]
  hex-interval-unselected = ["kevin.black","kevin.base05"]
  hex-layer-selected = ["kevin.white","kevin.base03"]
  hex-layer-unselected = ["kevin.black","kevin.base05"]
  packet-list-cell-focus = ["kevin.black","kevin.purple"]
  packet-list-cell-selected = ["kevin.black","kevin.base04"]
  packet-list-row-focus = ["kevin.black","kevin.cyan"]
  packet-list-row-selected = ["kevin.black","kevin.base05"]
  packet-struct-focus = ["kevin.black","kevin.cyan"]
  packet-struct-selected = ["kevin.black","kevin.base05"]
  progress-complete = ["kevin.white","kevin.purple"]
  progress-default = ["kevin.white","kevin.black"]
  progress-spinner = ["kevin.yellow","kevin.black"]
  spinner = ["kevin.yellow","kevin.white"]
  stream-client = ["kevin.white","kevin.red"]
  stream-match = ["kevin.white","kevin.yellow"]
  stream-search = ["kevin.white","kevin.black"]
  stream-server = ["kevin.cyan","kevin.blue"]
  title = ["kevin.red","unused"]
```
